apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260515-224615-80lm93u6679n-service
spec:
  selector:
    app: enterprise-system-20260515-224615-80lm93u6679n
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
